RPGSheet2/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RPGSheet2.Data;
using RPGSheet2.Models;

namespace RPGSheet2
{
    [Authorize]
    public class GamesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GamesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Games
        public async Task<IActionResult> Index()
        {
            return View(await _context.GetSearchGamesForUserAsync(User.GetUserId()));
        }

        // GET: Games/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Games
                .FirstOrDefaultAsync(m => m.SearchID == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        // GET: Games/Join
        public async Task<IActionResult> Join(string id)
        {
            SearchGame sgame = await SearchGame.Generate(_context,id);
            if (sgame == null) return RedirectToAction(nameof(Index));
            return View(JoinGame.FromSearchGame(sgame, User.GetUserId()));
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Join([Bind("GameID,GameName,OwnerName,UserID,password")] JoinGame jgame)
        {
            if (ModelState.IsValid)
            {
                Game game = _context.Games.First((g) => g.ID == jgame.GameID);

                if (game.Password == jgame.password)
                {
                    await _context.GrantUserAccessToGame(game, jgame.UserID,true);

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("password", "Password is incorrect.");
                    return View(jgame);
                }
            }
            ModelState.AddModelError("ModelOnly", "An unexpected error occured.");
            return View(jgame);
        }

        // GET: Games/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,Password")] CreateGame cgame)
        {
            if (ModelState.IsValid)
            {
                Game game = cgame.ToGame(User.GetUserId());
                _context.Add(game);
                await _context.SaveChangesAsync();
                game.AssignID();
                await _context.GrantUserAccessToGame(game, game.OwnerID);
                await _context.SaveChangesAsync();
                
                return RedirectToAction(nameof(Index));
            }
            return View(cgame);
        }

        // GET: Games/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = EditGame.GenerateAsync(_context, await _context.Games.FirstAsync((g) => g.SearchID == id));
            if (game == null)
            {
                return NotFound();
            }
            return View(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("GameID,SearchID,DisplayName,Description,Password")] EditGame egame)
        {
            if (id != egame.SearchID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Game game = egame.ToGame(_context);
                    _context.Update(game);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameExists(egame.SearchID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(egame);
        }

        // GET: Games/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = DeleteGame.Generate(_context, await _context.Games
                .FirstOrDefaultAsync(m => m.SearchID == id));
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var game = await _context.Games.FirstAsync((g) => g.SearchID == id);
            _context.Games.Remove(game);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GameExists(int id)
        {
            return _context.Games.Any(e => e.ID == id);
        }
        private bool GameExists(string id)
        {
            return _context.Games.Any(e => e.SearchID == id);
        }
    }
}

RPGSheet2/Controllers/TutorialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RPGSheet2.Data;
using RPGSheet2.Models;

namespace RPGSheet2.Controllers
{
    public class TutorialsController : Controller
    {
        private readonly ApplicationDbContext _context;
        public readonly IQueryable<IGrouping<string, TutorialPage>> tutquery;


        public TutorialsController(ApplicationDbContext context)
        {
            _context = context;
            tutquery = _context.TutorialPages.GroupBy((t) => t.Category);
        }

        // GET: Tutorials
        public async Task<IActionResult> Index(int? id)
        {
            ViewData["TutorialBar"] = true;
            ViewData["TutorialData"] = await tutquery.ToListAsync();

            var tutorialPage = await _context.TutorialPages
                .Include(t => t.Sections)
                .FirstOrDefaultAsync(m => m.ID == id);

            return View(tutorialPage);
        }

        // GET: Tutorials/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tutorials/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,Category")] TutorialPage tutorialPage)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tutorialPage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tutorialPage);
        }
        // GET: Tutorials/Create
        public async Task<IActionResult> Add(int? ID)
        {
            if (ID.HasValue)
            {
                ViewData["PageID"] = ID;
                return View();
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: Tutorials/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("Header,HTMLContent,PageID")] AddTutorialSection tutorialPage)
        {
            if (ModelState.IsValid)
            {
                if(tutorialPage.PageID <= 0)
                {
                    return RedirectToAction(nameof(Index));
                }
                TutorialSection tut = tutorialPage;
                tut.Page = await _context.TutorialPages.FirstOrDefaultAsync(t => t.ID == tutorialPage.PageID);
                
                _context.Add(tut);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index),new { id = tutorialPage.PageID });
            }
            return View(tutorialPage);
        }

        // GET: Tutorials/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tutorialSection = await _context.TutorialSections.Include(t => t.Page).FirstOrDefaultAsync(t => t.ID == id);
            if (tutorialSection == null)
            {
                return NotFound();
            }
            AddTutorialSection section = new AddTutorialSection(tutorialSection);
            return View(section);
        }

        // POST: Tutorials/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Header,HTMLContent,PageID")] AddTutorialSection tutorialSection)
        {
            if (id != tutorialSection.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    TutorialSection section = tutorialSection;
                    _context.Update(section);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index),new { id = tutorialSection.PageID });
            }
            return View(tutorialSection);
        }

        // GET: Tutorials/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tutorialPage = await _context.TutorialPages
                .FirstOrDefaultAsync(m => m.ID == id);
            if (tutorialPage == null)
            {
                return NotFound();
            }

            return View(tutorialPage);
        }

        // POST: Tutorials/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tutorialPage = await _context.TutorialPages.FindAsync(id);
            _context.TutorialPages.Remove(tutorialPage);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TutorialPageExists(int id)
        {
            return _context.TutorialPages.Any(e => e.ID == id);
        }
    }
}

RPGSheet2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RPGSheet2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">RPGSheet2</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Games" asp-action="Index">My Games</a></li>
                    <li><a asp-area="" asp-controller="Tutorials" asp-action="Index">Tutorials</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    @{
        bool? tutorialBar = ((bool?)ViewData["TutorialBar"]) ?? false;
        if (!tutorialBar.HasValue)
        {
            tutorialBar = false;
        }

        List<IGrouping<string, TutorialPage>> TutorialNavData = ViewData["TutorialData"] as List<IGrouping<string, TutorialPage>>;
        TutorialNavData = TutorialNavData ?? new List<IGrouping<string, TutorialPage>>();
    }
    @if (tutorialBar.Value)
    {
        <div class="listLeft col-lg-2" style="padding-left:0px">
            @await Html.PartialAsync("/Views/Tutorials/Partials/_TutNav_List.cshtml", TutorialNavData, ViewData)
        </div>
        <div class="body-content col-lg-10">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2019 - RPGSheet2</p>
            </footer>
        </div>
    }
    else
    {
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2019 - RPGSheet2</p>
            </footer>
        </div>
    }
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>